/*
  SCRIPT:   SES_OBJ_ACESSO2.SQL
  OBJETIVO: LISTAR O COMANDO DML EXECUTADO NO MOMENTO E DO TOTAL DE BLOCOS
            QUANTOS JA FORAM LIDOS
  AUTOR:    JOSIVAN
  DATA:     2000.02.08   
*/
SET LINE 400
SET PAGESIZE 50
--
COL MSG FORMAT A50
COL OBJECT_NAME FORMAT A15
--
SELECT VS.SID
      ,VS.OSUSER
      ,SUBSTR(AO.OBJECT_NAME,1,15)
      ,DECODE(VS.COMMAND,'2','INSERT'
                        ,'3','SELECT'
                        ,'6','UPDATE'
                        ,'7','DELETE'
                        ,'0','VAZIO')
      ,VSO.UPDATE_COUNT
      ,VSO.MSG
      ,VSO.STEPSOFAR
      ,VSO.STEPTOTAL
      ,TO_CHAR(VSO.START_TIME,'DD.MM  HH24:MI:SS')   INICIO
      ,TO_CHAR(VSO.CURRENT_TIME,'DD.MM  HH24:MI:SS') ACTUAL
      ,VSO.ELAPSED_SECONDS
  FROM V$SESSION_LONGOPS VSO
      ,V$SESSION VS
      ,DBA_OBJECTS AO
 WHERE VSO.SID   = VS.SID
   AND VSO.OBJID = AO.OBJECT_ID
   AND VS.OSUSER NOT IN ('oracle')
ORDER BY 2
/


SELECT VS.SID
      ,VS.OSUSER
      ,SUBSTR(AO.OBJECT_NAME,1,10)
      ,VSO.UPDATE_COUNT
      ,VSO.MSG
  FROM V$SESSION_LONGOPS VSO
      ,V$SESSION VS
      ,DBA_OBJECTS AO
 WHERE VSO.SID   = VS.SID
   AND VSO.OBJID = AO.OBJECT_ID
   AND VS.OSUSER NOT IN ('oracle')
ORDER BY 2
/
