/*
  SCRIPT:   SES_WAIT_2.SQL
  OBJETIVO: ACTUALIZAR AS ESTATISTICAS DOS INDEX
  AUTOR:    JOSIVAN
  DATA:     2000.02.08   
*/

SET ECHO OFF
SET PAGESIZE 50
SET LINESIZE 250
--
COLUMN PROGRAM FORMAT A15
COLUMN OSUSER FORMAT A12
COLUMN SID FORMAT 9999
COLUMN SQL_TEXT FORMAT A66
--
BREAK ON SID SKIP 1 ON SID ON SERIAL# ON OSUSER ON PROGRAM ON STATUS ON WAIT_TIME ON SECONDS_IN_WAIT ON STATE
--
  SELECT /*+ ORDERED */
         S.SID 
        ,S.SERIAL# 
        ,S.OSUSER 
        ,S.PROGRAM 
        ,S.STATUS 
        ,SW.WAIT_TIME 
        ,SW.SECONDS_IN_WAIT 
        ,SW.STATE 
        ,ST.SQL_TEXT
    FROM V$SESSION S 
        ,V$SQLTEXT ST 
        ,V$SESSION_WAIT SW
   WHERE S.SQL_ADDRESS = ST.ADDRESS
     AND S.SID         = SW.SID
     AND S.OSUSER     <> 'oracle'
ORDER BY 3,5
/
