/*
  SCRIPT:   SES_PLANO.SQL
  OBJETIVO: VERIFICAR OS USUARIOS CONNECTADOS AO BANCO E O COMANDO DML ATIVO
  AUTOR:    JOSIVAN
  DATA:     2000.02.08   
*/

SET ECHO OFF
SET LINESIZE 1500
SET PAGESIZE 50
--
COLUMN PROGRAM FORMAT A30
COLUMN SID FORMAT 9999
COLUMN USERNAME FORMAT A10
--
  SELECT S.SID
        ,S.SERIAL#
        ,S.OSUSER
        ,S.USERNAME
        ,SA.OPTIMIZER_MODE
        ,SA.ROWS_PROCESSED
        ,SA.PARSE_CALLS
        ,SA.EXECUTIONS
        ,SA.BUFFER_GETS
        ,SA.SQL_TEXT
    FROM V$SESSION S
        ,V$SQLAREA SA
   WHERE S.SQL_ADDRESS = SA.ADDRESS
     AND S.OSUSER <> 'oracle'
     AND SA.BUFFER_GETS > 0
ORDER BY 3
/
