/*
  SCRIPT:   SES_OBJ_ACESSO1.SQL
  OBJETIVO: LISTAR OS OBJETOS ACESSADOS PELO USUARIO
  AUTOR:    JOSIVAN
  DATA:     2000.02.08   
*/

SET LINE 200
SET PAGESIZE 50
--
COL OBJECT FORMAT A30
COL OWNER FORMAT A15
--
SELECT VA.SID
      ,VS.USERNAME
      ,VS.OSUSER
      ,VA.OWNER
      ,VA.OBJECT
      ,VA.TYPE
  FROM V$ACCESS VA
      ,V$SESSION VS
 WHERE VA.OWNER IN ('GALPDBA','GASDBA','TAPDBA')
   AND VA.SID = VS.SID
/
