/*
  SCRIPT:   SES_WAIT_1.SQL
  OBJETIVO: VERIFICAR OS USUARIOS CONNECTADOS AO BANCO E O COMANDO DML ATIVO COM SEU CUSTO
  AUTOR:    JOSIVAN
  DATA:     2000.02.08   
*/
--
SET ECHO OFF
SET PAGESIZE 50
SET LINESIZE 600
--
COLUMN PROGRAM  FORMAT A20
COLUMN OSUSER   FORMAT A12
COLUMN SID      FORMAT 9999
COLUMN USERNAME FORMAT A10
COLUMN SQL_TEXT FORMAT A100
--
BREAK ON SID SKIP 1
--
  SELECT S.SID
        ,S.SERIAL#
        ,S.LOCKWAIT
        ,SQ.OPTIMIZER_MODE          "TIPO"
        ,SQ.OPTIMIZER_COST          "CUSTO"
        ,S.OSUSER                   "USUARIO REDE"
        ,S.USERNAME
        ,SQ.ROWS_PROCESSED          "LINHAS"
        ,S.PROGRAM
        ,S.STATUS
        ,ST.SQL_TEXT
        ,SW.WAIT_TIME
        ,SW.SECONDS_IN_WAIT
        ,SW.STATE
    FROM V$SESSION S
        ,V$SQLTEXT ST
        ,V$SESSION_WAIT SW
        ,V$SQL SQ
   WHERE S.SQL_ADDRESS = ST.ADDRESS
     AND SQ.ADDRESS    = ST.ADDRESS
     AND S.SID         = SW.SID
     AND S.OSUSER     <> 'oracle'
     AND S.STATUS      = 'ACTIVE'
ORDER BY 1,2
/
CLEAR COLUMNS
