sqlplus apps/apps @ vw_usr.sqlaa        &
sqlplus apps/apps @ vw_usr.sqlab        &
sqlplus apps/apps @ vw_usr.sqlac        &
sqlplus apps/apps @ vw_usr.sqlad        &
sqlplus apps/apps @ vw_usr.sqlae        &
sqlplus apps/apps @ vw_usr.sqlaf        &
sqlplus apps/apps @ vw_usr.sqlag        &
sqlplus apps/apps @ vw_usr.sqlah        &
sqlplus apps/apps @ vw_usr.sqlai        &
sqlplus apps/apps @ vw_usr.sqlaj        &
sqlplus apps/apps @ vw_usr.sqlak        &
sqlplus apps/apps @ vw_usr.sqlal        &
sqlplus apps/apps @ vw_usr.sqlam        &
sqlplus apps/apps @ vw_usr.sqlan        &
sqlplus apps/apps @ vw_usr.sqlao        &
sqlplus apps/apps @ vw_usr.sqlap        &
sqlplus apps/apps @ vw_usr.sqlaq        &
sqlplus apps/apps @ vw_usr.sqlar        &
sqlplus apps/apps @ vw_usr.sqlas        &
sqlplus apps/apps @ vw_usr.sqlat        &
sqlplus apps/apps @ vw_usr.sqlau        &
sqlplus apps/apps @ vw_usr.sqlav        &
sqlplus apps/apps @ vw_usr.sqlaw        &
sqlplus apps/apps @ vw_usr.sqlax        &
sqlplus apps/apps @ vw_usr.sqlay        &
