#/bin/bash
# $Id$
# Marcus Vinicius Ferreira          ferreira.mv[ at ]gmail.com
#                 Aug/2008
#
# Backup mysql5 - Joyent
#

PATH=/opt/csw/mysql5/bin:/opt/csw/bin:opt/csw/sbin
PATH=$PATH:/opt/local/bin:/opt/local/sbin
PATH=$PATH:/usr/local/bin:/usr/local/sbin
PATH=$PATH:/usr/bin:/usr/sbin:/bin:/sbin

[ "$1" != '-f' ] && {
    echo
    echo "Usage: $0 -f"
    echo
    echo "    MySQL backup - create one dump file for each database."
    echo
    exit 1
}

 BKPDIR=/abd/bkp/depot/mysql
 LOGDIR=/abd/bkp/log
   FILE=${0##*/}
LOGFILE=${LOGDIR}/${FILE%.*}.log

MAIL_FROM="noreply@webcointernet.com"
  MAIL_TO="marcus.ferreira@abril.com.br"

### mysql:
###     GRANT select,lock tables,show databases,reload
###        ON *.*
###        TO backup@localhost IDENTIFIED BY 'Back-Up#2009';
###
DBUSER="backup"
DBPASS='Back-Up#2009'
DBHOST="localhost"

dtnow() {
    date "+%Y-%m-%d-%H%M"
}

logmsg() {
    echo "`date '+%Y-%m-%d %H:%M:%S'` : $1" | tee -a $LOGFILE
}

mailmsg() {
    MSG=$1
    ERROR=$2

    LINES=15
    LOG=`cat -n $LOGFILE | tail -${LINES}`

    [ "$ERROR" ] && MSG="WARNING: $MSG"

    mail $MAIL_TO <<MAIL
From: $MAIL_FROM
To: $MAIL_TO
Subject: ${HOSTNAME}: $MSG


$MSG

Message generated by $0 at `date`

Last $LINES lines at log $LOGFILE:
__________________________________________________________________

$LOG
__________________________________________________________________


MAIL
}

mysql_dump() {
    mysqldump -u $DBUSER -p${DBPASS}    \
        --add-drop-table    \
        --add-locks         \
        --all               \
        --create-options    \
        --disable-keys      \
        --extended-insert   \
        --flush-logs        \
        --hex-blob          \
        --quick             \
        --quote-names       \
        $1 | gzip > ${2}.gz
}

logmsg "MySQL Backup - Started."

DB_LIST=`mysqlshow -u $DBUSER -p${DBPASS} | awk '{print $2}' | egrep -v "Databases|^$"`
HOSTNAME=`hostname`
HOSTNAME=${HOSTNAME%%.*}

if [ ! "$DB_LIST" ]
then
    logmsg  "Database List empty. Backup will not be done."
    mailmsg "Database List empty. Backup will not be done." $ERR
    exit 4
fi

for DB in $DB_LIST
do
      DT=`dtnow`
    FILE="${BKPDIR}/${HOSTNAME}_${DT}_${DB}.mydump.sql"
    logmsg "Backup BEGIN [$DB]"
    logmsg "        file [$FILE]"

    if mysql_dump $DB $FILE
    then
        logmsg "Backup END   [$DB] - Ok"
    else
        ERR="$?"
        logmsg "Backup END   [$DB] - Error [$ERR]"
        mailmsg "MySQL did not finish backup: [$ERR]" $ERR
    fi

done

logmsg "MySQL Backup - Completed."

if [ "$ERR" ]
then
    exit $ERR
fi

mailmsg "MySQL Backup SUCCESS"
exit 0


