

CREATE TEMPORARY TABLESPACE temporary TEMPFILE 'F:\SUPORTEDBDC\ORADATA\ORAINS01\TEMPORARY_01.DBF' SIZE 500M AUTOEXTEND ON MAXSIZE 4G;
CREATE TEMPORARY TABLESPACE temporary TEMPFILE 'G:\SUPORTEDBDC\ORADATA\ORAINS01\TEMPORARY_01.DBF' SIZE 500M AUTOEXTEND ON MAXSIZE 4G;


CREATE TEMPORARY TABLESPACE temp      TEMPFILE 'H:\SUPORTEDBDC\ORADATA\ORAINS02\TEMPORARY.DBF'      SIZE 500M AUTOEXTEND ON MAXSIZE 4G;
CREATE TEMPORARY TABLESPACE temp      TEMPFILE 'L:\SUPORTEDBDC\ORADATA\ORAINS02\TEMP01.DBF'         SIZE 500M AUTOEXTEND ON MAXSIZE 4G;
